version: '2'
services:
  db:
    container_name: postgressql_container
    image: postgres:9.5
    volumes:
      - postgressql_container:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=craftworks
      - POSTGRES_USER=admin
      - POSTGRES_DB=tasksdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
volumes:
  postgressql_container: {}
